version: "2.20.2"

services:
  app:
    build: .
    ports:
      - 8081:8081
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD:?db password not set}
      - PG_DBNAME=${PG_DBNAME}
      - PG_PORT=${PG_PORT}
      - PG_HOST=${PG_HOST}
    volumes:
      - .:/app
    networks:
      - postgres
    depends_on:
      - "db"
    deploy:
      restart_policy:
        condition: on-failure

  db:
    container_name: postgresdb # never do this in a production environment!
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DBNAME}
      - PGDATA= /var/lib/postgresql/pgdata
    networks:
      - postgres
    volumes:
      - pgdata:/var/lib/postgresql
    restart: always

volumes:
  pgdata:
    external: true
    name: postgres_data

networks:
  postgres:
    driver: bridge
